services:
  - type: web
    name: angelkellogg-api
    env: node
    region: oregon
    plan: starter
    buildCommand: "npm ci && npm run build"
    startCommand: "npm start"
    healthCheckPath: "/health"
    envVars:
      - key: NODE_VERSION
        value: 18
